config/routes.rb
Tasks::Application.routes.draw do
  root :to => 'Tasks#index'
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :task
  validates :task, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  	@task = Task.new
  	@tasks = Task.all
  end
  
  def create
  	#render :text => params.inspect
  	Task.create params[:task]
  	redirect_to :back
  end

  def edit
  	@task = Task.find params[:id]
  end

  def update
  	task = Task.find params[:id]
  	if task.update_attributes params[:task]
  		redirect_to tasks_path, :notice => "Your task has successfully been updated."
  	else
  		redirect_to :back, :notice => "There was an error updating your task."
  	end
  end

  def destroy
  	Task.destroy params[:id]
  	redirect_to :back, :notice => "Task has been deleted"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container" >
<% flash.each do |name, message| %>
<!--<div id="flash_<%= name %>">
<%= message %>
</div>-->
<!--<%= content_tag :div, message, :id => "flash_#{name}" %>-->
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <%= message %>
</div>

<% end %>
<div class="row">
<div class="span5 offset3 mini-layout">
	<i class="icon-check-task"></i><h1 class="title">Tasks</h1>
    <%= yield %>  
</div>
</div>
</div>


</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<div class="input-append">
	<%= f.label :task %>
	<%= f.text_field :task, :"x-webkit-speech" => "", :speech => "", :class => 'span4', :style => "height:26px" %>
	<%= f.submit submit, :class => 'btn btn-primary btn-large' %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h3>Edit Tasks</h3>
<%= render 'form', :submit => "Update Task" %>

app/views/tasks/index.html.erb
<h4>Add Tasks</h4>
<%= render 'form', :submit => "Create Task" %>
<table class="table">
	<thead>
	<tr>
		<th> </th>
	</tr>
	</thead>
	<% for task in @tasks %>
	<tr>
	<td id="task_<%= task.id %>">
		<%= task.task %>
		<span> 
		<%= link_to (raw("<i class='icon-pencil-task'></i>")), edit_task_path(task), :title => 'Edit', :name => 'Edit' %>
		<%= link_to (raw("<i class='icon-trash-task'></i>")), task, :method => 'delete', :title => 'Delete' %>
		</span>
	</td>
	</tr>
	<% end %>
</table>